-- CREATE TABLE summary3 (classe string,
--  np int,
--  n int,
--  nnodesb float,
--  compb float,
--  timeb float,
--  maxndb float,
--  hvb float,
--  time0 float,
--  nsol0 float,
--  hv0 float,
--  comp0 float,
--  time2 float,
--  nsol2 float,
--  hv2 float,
--  comp2 float,
--  time3 float,
--  nsol3 float,
--  hv3 float,
--  comp3 float);
SELECT
  classe,
  np,
  n,
  printf("%.1f", nnodesb) nnodesb,
  printf("%.1f", timeb) timeb,
  printf("%.1f", nsol0) nsol_sce,
  printf("%.1f", time0) time_sce_list,
  printf("%.1f", time2) time_sce_2dt,
  printf("%.1f", time2/time0) speed_up_2dt,
  printf("%.1f", comp2/comp0) comp_ratio_2dt,
  printf("%.1f", time3) time_sce_3dt,
  printf("%.1f", time3/time0) speed_up_3dt,
  printf("%.1f", comp3/comp0) comp_ratio_3dt,
  printf("%.1f", 100*hv0/hvb) quality
from summary3;

