all:
	gnuplot hard.plt
	latex hard.tex
	dvipdf hard.dvi

	gnuplot easy.plt
	latex easy.tex
	dvipdf easy.dvi

	gnuplot comp_easy.plt
	latex comp_easy.tex
	dvipdf comp_easy.dvi

	gnuplot comp_hard.plt
	latex comp_hard.tex
	dvipdf comp_hard.dvi

	gnuplot hist.plt
	latex lpgavsmip.tex
	dvipdf lpgavsmip.div
	latex lptsvsmip.tex
	dvipdf lptsvsmip.dvi
