:o tools/mokp.c
:tabnew models/mokp/mokp.c
:vsplit models/mokp/mokp.h
:tabnew models/mokp/bazgan.c
:vsplit models/mokp/bazgan.h
:tabnew utils/kdtree.c
:vsplit utils/kdtree.h
:tabnew utils/avl.c
:vsplit utils/avl.h
